drop table if exists country cascade;

create table country (
  id bigint generated by default as identity primary key,
  name varchar(50) not null
);


drop table if exists competition cascade;

create table competition (
  id bigint generated by default as identity primary key,
  name varchar(50) not null
);


drop table if exists team cascade;

create table team (
  id bigint generated by default as identity primary key,
  name varchar(30) not null,
  logo_url text not null,
  fk_country_id bigint not null references country
);


drop table if exists player cascade;

create table player (
  id bigint generated by default as identity primary key,
  name varchar(30) not null,
  fk_team_id bigint not null references team
);


drop table if exists match cascade;

create table match (
  id bigint generated by default as identity primary key,
  fk_left_team_id bigint not null references team,
  fk_right_team_id bigint not null references team,
  fk_league_id bigint not null references competition,
  datetime timestamp with time zone not null,
  left_score smallint not null,
  right_score smallint not null,
  finished boolean not null
);


drop table if exists "user" cascade;

create table "user" (
  id bigint generated by default as identity primary key,
  username varchar(30) not null,
  email text not null,
  hashed_password text not null,
  is_admin boolean not null default false
);


drop table if exists favourite_team;

create table favourite_team (
  fk_user_id bigint not null references "user",
  fk_team_id bigint not null references team,
  primary key (fk_user_id, fk_team_id)
)